filebeat.prospectors:
- type: log
  paths:
    - /home/vagrant/logFile.log
  fields:
    document_type: springboot

output.logstash:
  enabled: true
  hosts: ["192.168.56.61:5044"]

#logging.level: info
#logging.to_files: true
#logging.files:
 # path: /var/log/filebeat/
 # name: filebeat.log
 # rotateeverybytes: 10485760
 # keepfiles: 20

