apiVersion: v1
kind: Service
metadata:
  name: web-second
  namespace: {{.Values.namespace}}
  labels:
    run: web-second
spec:
  externalIPs:
   -  10.7.96.32
  ports:
    # the port that this service should serve on
#    - port: 80
    - port: 443
  # label keys and values that must match in order to receive traffic for this service
  selector:
    run: web-second
