- name: Creates directory Build
  file:
    path: /certs
    state: directory
    owner: root
    group: root
    mode: 0755

- copy:
    src: "{{ role_path }}/files/domain.crt"
    dest: /certs/domain.crt
    owner: root
    group: root
    mode: 0755

- copy:
    src: "{{ role_path }}/files/domain.key"
    dest: /certs/domain.key      
    owner: root
    group: root
    mode: 0755

- name: Docker dir cert
  file:
    path: /etc/docker/certs.d
    state: directory
    owner: root
    group: root
    mode: 0755


- name: Docker cert
  file:
    path: /etc/docker/certs.d/myreg.com:5000
    state: directory
    owner: root
    group: root
    mode: 0755

- copy:
    src: "{{ role_path }}/files/domain.crt"
    dest: /etc/docker/certs.d/myreg.com:5000/ca.crt
    owner: root
    group: root
    mode: 0755

- name: add hosts
  shell: |
        echo 192.168.56.81   myreg.com >> /etc/hosts


- name: Creates directory Build
  file:
    path: /home/helm
    state: directory
    owner: root
    group: root
    mode: 0755

- copy:
    src: "{{ role_path }}/files/helloworld"
    dest: /home/helm/
    owner: root
    group: root
    mode: 0755

- name: run repo
  run_once: true
  delegate_to: node1
  shell: |
     cd / && docker run -d --restart=always --name registry -v `pwd`/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 5000:5000 registry:2
