apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{.Values.namespace}}
  labels:
    run: redis
#    context: docker-k8s-lab
spec:
#  externalIPs:
#   - 192.168.56.12
  ports:
    # the port that this service should serve on
    - port: 6379
  # label keys and values that must match in order to receive traffic for this service
  selector:
    run: redis
