apiVersion: v1
kind: Service
metadata:
  name: {{.Values.namefromvalue}}
  labels:
    run: {{.Values.namefromvalue}}
spec:
  externalIPs:
   - 192.168.56.82
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
#    - port: 443
  # label keys and values that must match in order to receive traffic for this service
  selector:
    run: {{.Values.namefromvalue}}
